ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/config/routes.rb
Poc015AutocompleteMongoidRails::Application.routes.draw do
  resources :brands

  get "welcome/showrails"

  get "welcome/g"

  get "welcome/controller"

  get "welcome/welcome"

  get "welcome/show"

  get 'welcome/autocomplete_brand_name'

  root :to => "welcome#show"
end

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/models/brand.rb
class Brand
  include Mongoid::Document
  field :name, type: String
end

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  #autocomplete :Brand, :name


  def showrails
  end

  def g
  end

  def controller
  end

  def welcome
  end

  def show
  end

  def autocomplete_brand_name
    @brand = Brand.each
    puts "Executando autocomplete_brand_name"
    render :json => @brand
  end

end

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/helpers/brands_helper.rb
module BrandsHelper
end

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.name %></td>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand', new_brand_path %>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brand.name %>
</p>


<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>

    <%= csrf_meta_tag %>
    <%= yield(:head) %>





  <!-- AUTOCOMPLETE -->
  <script>
  $(function() {
    function log( message ) {
      $( "<div/>" ).text( message ).prependTo( "#log" );
      $( "#log" ).scrollTop( 0 );
    }

    $( "#birds" ).autocomplete({
      source: "http://localhost:3000/welcome/autocomplete_brand_name.json",
      minLength: 2,
      select: function( event, ui ) {
        log( ui.item ? "Selected: " + ui.item + " aka " + ui.item.id : "Nothing selected, input was " + this.value );
      }
    });
  });
  </script>
  <!-- AUTOCOMPLETE -->


  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/welcome/controller.html.erb
<h1>Welcome#controller</h1>
<p>Find me in app/views/welcome/controller.html.erb</p>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/welcome/g.html.erb
<h1>Welcome#g</h1>
<p>Find me in app/views/welcome/g.html.erb</p>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>


<h1>Welcome!</h1>
<%= form_tag do %>
<div class="demo">

<div class="ui-widget">
	<label for="birds">Birds: </label>
	<input id="birds" />
</div>
</div>

<% end %>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/welcome/showrails.html.erb
<h1>Welcome#showrails</h1>
<p>Find me in app/views/welcome/showrails.html.erb</p>

ESubscriber Project/ESub Poc/ESub User/poc015-autocomplete-mongoid-rails/app/views/welcome/welcome.html.erb
<h1>Welcome#welcome</h1>
<p>Find me in app/views/welcome/welcome.html.erb</p>